{
    "docs": "https://docs.ansible.com/ansible-core/2.13/dev_guide/testing/sanity/import.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test import --python 3.8` [[explain](https://docs.ansible.com/ansible-core/2.13/dev_guide/testing/sanity/import.html)] failed with 1 error:", 
            "output": "plugins/httpapi/httpapi.py:12:1: traceback: SyntaxError: from __future__ imports must occur at the beginning of the file"
        }
    ], 
    "verified": false
}
