{
    "docs": "https://docs.ansible.com/ansible-core/2.13/dev_guide/testing/sanity/pylint.html", 
    "results": [
        {
            "message": "The test `ansible-test sanity --test pylint` [[explain](https://docs.ansible.com/ansible-core/2.13/dev_guide/testing/sanity/pylint.html)] failed with 1 error:", 
            "output": "plugins/httpapi/httpapi.py:85:12: disallowed-name: Disallowed name \"_\""
        }
    ], 
    "verified": false
}
